image: atlassian/default-image:2

pipelines:
  custom: # Pipelines that can only be triggered manually
    dev:
      - step:
          script:
            - add-apt-repository ppa:nilarimogard/webupd8
            - apt-get update
            - apt-get -y install python-wxgtk2.8
            - apt-get -y install xvfb x11-xkb-utils
            - apt-get -y install firefox xvfb
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install robotframework
            - pip install robotframework-xvfb
            - pip install selenium
            - pip install -U requests
            - pip install -U robotframework-requests
            - pip install robotframework-imaplibrary
            - pip install robotframework-selenium2library
            - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux32.tar.gz
            - tar -xvzf geckodriver-v0.23.0-linux32.tar.gz
            - chmod +x geckodriver
            - mv geckodriver /usr/local/bin/
            - robot -v browser:xvfb -v password_adm:srx-group -v email_adm:srx-group+dev@agilevision.io -v host_adm:admin-dev.storeroomlogix.com -v email_dist:srx-group+dev-distributor@agilevision.io -v password_dist:srx-group -v host_dist:distributor-dev.storeroomlogix.com -v email_cust:srx-group+dev-customer@agilevision.io -v password_cust:srx-group -v host_cust:customer-dev.storeroomlogix.com -v RFID_SN:RFID230820106808 -v environment:dev -v API_key:m4DAfPuRurdzlsVrlen2 -v email_perm:srx-group+dev-permissions@agilevision.io -v password_perm:srx-group test-cases
          artifacts:
            - test-results/**