image: atlassian/default-image:2

pipelines:
  custom: # Pipelines that can only be triggered manually
    robot:
      - step:
          script:
            - add-apt-repository ppa:nilarimogard/webupd8
            - apt-get update
            - apt-get -y install firefox xvfb
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install robotframework
            - pip install robotframework-xvfb
            - pip install selenium
            - pip install -U requests
            - pip install -U robotframework-requests
            - pip install robotframework-selenium2library
            - pip install robotframework-sshlibrary
            - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux32.tar.gz
            - tar -xvzf geckodriver-v0.24.0-linux32.tar.gz
            - chmod +x geckodriver
            - mv geckodriver /usr/local/bin/
            - export PYTHONWARNINGS="ignore"
            - robot -v set:dev.robot -v browser:xvfb test-cases
  custom: # Pipelines that can only be triggered manually
    pybot:
      - step:
          script:
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - sudo apt-get install python
            - python get-pip.py
            - pip install selenium
            - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux32.tar.gz
            - tar -xvzf geckodriver-v0.25.0-linux32.tar.gz
            - chmod +x geckodriver
            - mv geckodriver /usr/local/bin/
            - export PYTHONPATH=$PYTHONPATH:./srx-pybot/
            - python srx-pybot/src/suites/main_suite.py fhl
