version: 0.2

phases:
  build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:./srx-pybot/
      - pytest -m regression --browser_name=chrome-headless --environment=qa --credentials --admin_email=$ADMIN_EMAIL --admin_password=$ADMIN_PASSWORD --distributor_email=$DISTRIBUTOR_EMAIL --distributor_password=$DISTRIBUTOR_PASSWORD --customer_email=$CUSTOMER_EMAIL --customer_password=$CUSTOMER_PASSWORD --checkout_group_email=$CHECKOUT_GROUP_EMAIL --checkout_group_password=$CHECKOUT_GROUP_PASSWORD --cognito_user_pool_id=$USER_POOL_ID --cognito_client_id=$CLIENT_ID --cognito_client_secret=$CLIENT_SECRET --cognito_checkout_client_id=$CHECKOUT_CLIENT_ID --testrail_email=$TESTRAIL_EMAIL --testrail_password=$TESTRAIL_PASSWORD .