version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws s3 cp src/erp_emulator s3://${BUCKET_NAME}/erp_emulator --recursive
      - export AUTOMATION_INSTANCE_ID=$(aws ec2 describe-instances --filters 'Name=tag:Name,Values='"${AUTOMATION_INSTANCE_NAME}" --output text --query 'Reservations[*].Instances[*].InstanceId')
      - export S3_BUCKET=${BUCKET_NAME}
      - aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":['\""${AUTOMATION_INSTANCE_ID}"\"']}]' --parameters '{"commands":["aws s3 cp s3://ilx-mock-server-code-qa/erp_emulator /home/ec2-user/automation --recursive"],"workingDirectory":[""],"executionTimeout":["600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region us-east-1 --cloud-watch-output-config "CloudWatchOutputEnabled=true,CloudWatchLogGroupName=/aws/ssm/ilx-erp-emulation-update-qa"
      - aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":['\""${AUTOMATION_INSTANCE_ID}"\"']}]' --parameters '{"commands":["sudo nohup python3 /home/ec2-user/automation/server.py > /home/ec2-user/automation/log.txt 2>&1 &"],"workingDirectory":[""],"executionTimeout":["600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region us-east-1 --cloud-watch-output-config "CloudWatchOutputEnabled=true,CloudWatchLogGroupName=/aws/ssm/ilx-erp-emulation-update-qa"
