version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
    runtime-versions:
      python: 3.8
  build:
    commands:
      - scp -i $KEY /src/erp_emulator ec2-user@$IP:/home/ec2-user